version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  maeFarGate:1 .
      - docker tag maeFarGate:1 934139732129.dkr.ecr.us-east-2.amazonaws.com/maepoc
  post_build:
    commands: 
      - echo Build completed on `date`
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - echo Pushing the Docker image...
      - docker push 934139732129.dkr.ecr.us-east-2.amazonaws.com/maepoc
